### ISSUE TITLE
PUT Accounts/id Cannot Handle Password Property with Empty String.

### ISSUE THREAD

**Issue by twinmind** [cornflourblue/aspnet-core-3-signup-verification-api#1]
When running together with [react app](https://github.com/cornflourblue/react-signup-verification-boilerplate), editing existing user creates a payload like this 
```json
{"title":"Mr","firstName":"John","lastName":"Smith","email":"john@smith.com","role":"User","password":"","confirmPassword":""}
```
And this results in error like on the screenshot.
![bad_request](https://user-images.githubusercontent.com/9801734/87219591-671c7500-c311-11ea-9844-3019bc57d503.png)
If payload is replaced with nulls, i.e. 
```json
{"title":"Mr","firstName":"John","lastName":"Smith","email":"john@smith.com","role":"User","password":null,"confirmPassword":null}
```
Then it works fine.

My guess is that the attribute `[MinLength(6)]` on `Password` property in `UpdateRequest` model doesn't allow empty string, but is happy with null.

**Comment by cornflourblue** [comment]
Thanks Alexey, I've just updated the `UpdateRequest.cs` model to allow empty strings for all parameters - https://github.com/cornflourblue/aspnet-core-3-signup-verification-api/blob/master/Models/Accounts/UpdateRequest.cs
