### ISSUE TITLE
How I can consume this API in MVC client?

### ISSUE THREAD

**Issue by iozcelik** [cornflourblue/aspnet-core-3-signup-verification-api#17]
I am learning security for API and I want to implement in client MVC application. However, I don't find any good example or tutorial for MVC client. Lots of examples explain, how consume in SPAs.

**Comment by AcidRaZor** [comment]
Did you read the article examples? It includes both Angular and React examples for you

https://jasonwatmore.com/post/2020/07/06/aspnet-core-3-boilerplate-api-with-email-sign-up-verification-authentication-forgot-password#running-react

**Comment by iozcelik** [comment]
Yes, I read all of them. However, I dont want to use SPA. I try to use MVC, httpclientfactory and requestdelegate.

**Comment by AcidRaZor** [comment]
I just googled "Consume an API in C#"

This was it's top result: https://www.c-sharpcorner.com/article/consuming-asp-net-web-api-rest-service-in-asp-net-mvc-using-http-client/

It explains how to make WebAPI calls from an MVC application using HttpClient. If there is a specific implementation you're after using HttpClientFactory and a RequestDelegate, I will leave that up to your skills to figure out. However, abovementioned URL will get you going and is not an SPA

**Comment by iozcelik** [comment]
Thanks, I also found that solution too. However, your api implementation seems better than others (also I googled it), so I want to ask you. 

Everybody makes different. I am new .net core web world. Until this time, I write background services. So I try to figured out how I will do better. 

Thanks for answers.
