### ISSUE TITLE
Long Lived JWT Refresh Token is being Revoked and Replaced on Every Short Living Token Refresh Request

### ISSUE THREAD

**Issue by twinmind** [cornflourblue/aspnet-core-3-signup-verification-api#2]
Every time web application calls `accounts/refresh-token`, the long lived token is being replaced along with short lived token and new record is created in `RefreshToken` table.

**Comment by cornflourblue** [comment]
This behaviour is intentional for increased security, the technique is called _refresh token rotation_, there's more info at this article - https://auth0.com/docs/tokens/concepts/refresh-token-rotation
