### ISSUE TITLE
Redundant Dollar Sign In Email Body.

### ISSUE THREAD

**Issue by twinmind** [cornflourblue/aspnet-core-3-signup-verification-api#3]
There is no need for dollar sign inside the string next to variable opening curly brace on these lines:
https://github.com/cornflourblue/aspnet-core-3-signup-verification-api/blob/c8d1607fb70a0f73611080be7dbab412b227deca/Services/AccountService.cs#L374
https://github.com/cornflourblue/aspnet-core-3-signup-verification-api/blob/c8d1607fb70a0f73611080be7dbab412b227deca/Services/AccountService.cs#L384
It currently simply adds a dollar sign to a string content, and in case of line 384 it breaks reset password link.

**Comment by cornflourblue** [comment]
fix merged
